FROM selenoid/opera:@@VERSION@@

USER root

RUN \
	apt-get update && \
	apt-get -y --no-install-recommends install x11vnc fluxbox && \
	apt-get clean && \
	rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*

USER selenium

COPY entrypoint.sh /