FROM selenoid/dev_firefox:@@VERSION@@

COPY geckodriver /usr/bin/
COPY selenoid /usr/bin/
COPY browsers.json /etc/selenoid/
COPY entrypoint.sh /

USER selenium

EXPOSE 4444
ENTRYPOINT ["/entrypoint.sh"]
