FROM selenoid/dev_firefox:@@VERSION@@

COPY geckodriver /usr/bin/
COPY selenoid /usr/bin/
COPY browsers.json /etc/selenoid/
COPY entrypoint.sh /

RUN \
        apt-get update && \
        apt-get -y --no-install-recommends install pulseaudio fluxbox x11-utils && \
        apt-get clean && \
        adduser --system --home /home/selenium \
        --ingroup nogroup --disabled-password --shell /bin/bash selenium && \
        rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*
USER selenium

EXPOSE 4444
ENTRYPOINT /entrypoint.sh
