FROM selenoid/dev:firefox_@@VERSION@@

ARG PORT
ARG SCREEN_RESOLUTION

COPY geckodriver /usr/bin/

EXPOSE $PORT
CMD ["/usr/bin/xvfb-run", "-a", "-s", "'-screen 0 $SCREEN_RESOLUTION -noreset'", "/usr/bin/geckodriver", "--host", "::", "--port", "$PORT", "--log", "debug"]
