FROM selenoid/dev:firefox_@@VERSION@@

COPY geckodriver /usr/bin/

EXPOSE 4444
CMD ["/usr/bin/xvfb-run", "-a", "-s", "'-screen 0 1920x1080x24 -noreset'", "/usr/bin/geckodriver", "--host", "::", "--port", "4444", "--log", "debug"]
