FROM selenoid/dev:opera_@@VERSION@@

COPY selenium-server-standalone.jar /usr/share/selenium/

EXPOSE 4444
CMD ["/usr/bin/xvfb-run", "-a", "-s", "'-screen 0 1920x1080x24 -noreset'", "/usr/bin/java", "-jar", "/usr/share/selenium/selenium-server-standalone.jar", "-port", "4444", "-timeout", "60", "-browserTimeout", "120", "-newSessionWaitTimeout", "10000"]
