FROM selenoid/base:2.0@@REQUIRES_JAVA@@

ARG VERSION
ARG CLEANUP

RUN  \
        ( [ "$CLEANUP" != "true" ] && rm -f /etc/apt/apt.conf.d/docker-clean ) || true && \
        apt-get update && \
        apt-get -y --no-install-recommends install pulseaudio firefox=$VERSION && \
        ($CLEANUP && rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*) || true

RUN \
        adduser --system --home /home/selenium \
        --ingroup nogroup --disabled-password --shell /bin/bash selenium && \
        usermod -a -G sudo selenium && \
        echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN mkdir /video

RUN chown selenium /video /var/log

USER selenium
