FROM selenoid/firefox:@@VERSION@@

RUN \
	apt-get update && \
	apt-get -y --no-install-recommends install x11vnc && \
	apt-get clean && \
	rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*

COPY entrypoint.sh /