FROM selenoid/dev_chrome:@@VERSION@@


COPY chromedriver /usr/bin/
COPY entrypoint.sh /

RUN \
        apt-get update && \
        apt-get -y install fluxbox x11-utils && \
        apt-get clean && \
        rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*
RUN \
        adduser --system --home /home/selenium \
        --ingroup nogroup --disabled-password --shell /bin/bash selenium && \
        chmod +x /usr/bin/chromedriver
USER selenium

EXPOSE 4444
ENTRYPOINT /entrypoint.sh