FROM selenoid/dev:chrome_@@VERSION@@

COPY chromedriver /usr/bin/

EXPOSE 4444
CMD ["/usr/bin/xvfb-run", "-a", "-s", "'-screen 0 1920x1080x24 -noreset'", "/usr/bin/chromedriver", "--port=4444", "--whitelisted-ips=''", "--verbose"]
