FROM selenoid/dev:opera_@@VERSION@@

COPY operadriver /usr/bin/

EXPOSE 4444
CMD ["/usr/bin/xvfb-run", "-a", "-s", "'-screen 0 1920x1080x24 -noreset'", "/usr/bin/operadriver", "--port=4444", "--whitelisted-ips=''", "--verbose"]
