FROM selenoid/dev_opera:@@VERSION@@

COPY operadriver /usr/bin/
COPY entrypoint.sh /

RUN \
        adduser --system --home /home/selenium \
        --ingroup nogroup --disabled-password --shell /bin/bash selenium && \
        chmod +x /usr/bin/operadriver
USER selenium

EXPOSE 4444
ENTRYPOINT /entrypoint.sh
